[tox]
; py3.7 runs into aiocoap unrelated trouble in setups on Debian sid, leaving
; this to `setup.py test` for now
;
; For uvloop not being tested with pyp3, see
; https://github.com/chrysn/aiocoap/issues/193.
envlist = {py37,py38,py39,py310,py311,pypy3}-{noextras,allextras},py38-uvloop

[testenv]
deps =
    coverage
    pytest

allowlist_externals = /bin/sh
commands =
    python -m coverage run --parallel -m aiocoap.cli.defaults
    # PyPy coverage is just too slow for many time critical tests, see https://github.com/chrysn/aiocoap/issues/265
    sh -c 'if python3 --version |grep -iq pypy; then \
    python -Xdev -m pytest {posargs}; \
    else\
    python -Xdev -m coverage run --parallel -m pytest {posargs}; \
    fi'

[testenv:{py37,py38,py39,py310,pypy3}-noextras]
description = Running on plain Python

[testenv:{py37,py38,py39,py310,pypy3}-allextras]
description = Running with all extra dependencies installed
extras =
    all

setenv =
    AIOCOAP_DEFAULTS_EXPECT_ALL=1

[testenv:{py38,pypy3}-uvloop]
description = Running on uvloop
deps =
    coverage
    uvloop
extras =
    all
; client-/server-transport could just as well be done on the default main loop,
; but AFAIR uvloop required occasional workarounds
setenv =
    AIOCOAP_TESTS_LOOP=uvloop
    AIOCOAP_CLIENT_TRANSPORT=oscore:simple6
    AIOCOAP_SERVER_TRANSPORT=oscore:simplesocketserver
